### ISSUE TITLE
Please correct version number to 2.17 in id.

### ISSUE THREAD

**Issue by SzotsGabor** [cjbolt/EubosChess#7]
Or am I testing v2.16?

**Comment by cjbolt** [comment]
The version number was definitely incorrect. Without doing quite a lot of forensics on the binary .jar file I can't be 100% sure whether the old file just had the wrong version number or whether it was actually truly v2.16 and as such didn't have the IID fix.

In any event I have updated the checked in binary so that it is correct and updated the file attached with the v2.17 release.

Sorry, for the confusion.
Chris

**Comment by SzotsGabor** [comment]
What now I can see at Assets is a batch file and the source. In the latter I find a jar file which is identical with what I have been using and displays this:
id name Eubos 2.16
id author Chris Bolt
option name Hash type spin default 256 min 32 max 4000
option name Threads type spin default 2 min 1 max 4
option name Move Overhead type spin default 10 min 0 max 5000
option name Lazy Threshold type spin default 275 min 0 max 1000
uciok

This is different from the file I can download at version 2.16 so most probably it is version 2.17 in disguise.

**Comment by cjbolt** [comment]
Unfortunately the upload failed, and I didn't realise it had failed. 
![upload_failed](https://user-images.githubusercontent.com/11176365/213792525-fab50082-9689-4419-afdc-140d92c44b95.png)
I have remedied it now.
